-- Raise autogenerated NPCBot entry floor after expanding base templates to 70600-72799.
-- Required when upgrading worldserver with BOT_ENTRY_CREATE_BEGIN = 73000.
UPDATE `worldstates` SET `value` = GREATEST(`value`, 72999) WHERE `entry` = 70000 AND `value` < 73000;
