# By leewheel 20260529 - locate CUDA Toolkit for NpcBot LLM (VS CMake often lacks CUDA_PATH).
function(npcbot_setup_cudatoolkit_root)
  if(CUDAToolkit_ROOT)
    return()
  endif()

  if(DEFINED ENV{CUDA_PATH} AND EXISTS "$ENV{CUDA_PATH}/include/cuda.h")
    set(CUDAToolkit_ROOT "$ENV{CUDA_PATH}" CACHE PATH "NVIDIA CUDA Toolkit root" FORCE)
    message(STATUS "NpcBot CUDA: using CUDA_PATH=${CUDAToolkit_ROOT}")
    return()
  endif()

  if(WIN32)
    set(_cuda_search_bases)
    if(DEFINED ENV{ProgramFiles})
      list(APPEND _cuda_search_bases "$ENV{ProgramFiles}/NVIDIA GPU Computing Toolkit/CUDA")
    endif()
    list(APPEND _cuda_search_bases "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA")

    foreach(_cuda_base IN LISTS _cuda_search_bases)
      if(NOT EXISTS "${_cuda_base}")
        continue()
      endif()
      file(GLOB _cuda_versions LIST_DIRECTORIES true "${_cuda_base}/v*")
      if(NOT _cuda_versions)
        continue()
      endif()
      list(SORT _cuda_versions COMPARE NATURAL)
      list(REVERSE _cuda_versions)
      foreach(_cuda_dir IN LISTS _cuda_versions)
        if(EXISTS "${_cuda_dir}/include/cuda.h")
          set(CUDAToolkit_ROOT "${_cuda_dir}" CACHE PATH "NVIDIA CUDA Toolkit root" FORCE)
          message(STATUS "NpcBot CUDA: auto-detected CUDAToolkit_ROOT=${CUDAToolkit_ROOT}")
          return()
        endif()
      endforeach()
    endforeach()
  endif()
endfunction()
